version: "3.9"

services:
  web:
    build: ./
    container_name: denwallo_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - denwallo_net

  db:
    image: mysql:8.0
    container_name: denwallo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: denwallo
      MYSQL_USER: denuser
      MYSQL_PASSWORD: denpass
    volumes:
      - db_data:/var/lib/mysql
      - ./database/denwallo.sql:/docker-entrypoint-initdb.d/denwallo.sql
    networks:
      - denwallo_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: denwallo_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - denwallo_net

volumes:
  db_data:

networks:
  denwallo_net:
    driver: bridge